"""
Sugestões de música por lição. Uma música em inglês cuja letra ou tema toca
o foco gramatical, lexical ou cultural da lição.
Cobre 189 lições (não-Review) dos 6 cursos.
"""

MUSIC: dict[str, dict[str, dict]] = {
    "starter": {
        "1A":  {"title": "Hello", "artist": "Adele", "why": "Verb be + saudações simples (Hello, it's me)."},
        "1B":  {"title": "We Are the World", "artist": "USA for Africa", "why": "Países e nacionalidades, plural we are."},
        "PE1": {"title": "ABC", "artist": "The Jackson 5", "why": "O alfabeto em inglês cantado letra a letra."},
        "2A":  {"title": "Englishman in New York", "artist": "Sting", "why": "Nacionalidades; ‘I'm an Englishman in New York’."},
        "2B":  {"title": "867-5309 / Jenny", "artist": "Tommy Tutone", "why": "Phone numbers — a letra é literalmente um telefone."},
        "3A":  {"title": "Lost", "artist": "Coldplay", "why": "Substantivos / coisas perdidas (objetos pequenos do dia a dia)."},
        "3B":  {"title": "Memories", "artist": "Maroon 5", "why": "Souvenirs / coisas que lembramos; tema this/that/these/those."},
        "PE2": {"title": "Black Coffee", "artist": "Peggy Lee", "why": "Comprar café / pedir bebida (Practical English context)."},
        "4A":  {"title": "We Are Family", "artist": "Sister Sledge", "why": "Família, possessivos (my sister, my brother)."},
        "4B":  {"title": "Pink Cadillac", "artist": "Bruce Springsteen", "why": "Cores + carros (4B é sobre buying a car)."},
        "5A":  {"title": "Sugar, Sugar", "artist": "The Archies", "why": "Comida e bebida no presente simples."},
        "5B":  {"title": "Leaving on a Jet Plane", "artist": "John Denver", "why": "Viagem de avião — contexto direto de 5B."},
        "PE3": {"title": "Time", "artist": "Pink Floyd", "why": "Tema central: ‘telling the time’."},
        "6A":  {"title": "9 to 5", "artist": "Dolly Parton", "why": "Profissões e rotina de trabalho (3rd person simple present)."},
        "6B":  {"title": "Good Morning, Good Morning", "artist": "The Beatles", "why": "Rotina diária; ‘good morning, good night’ no título."},
        "7A":  {"title": "Saturday Night", "artist": "Bay City Rollers", "why": "Atividades de fim de semana e tempo livre."},
        "7B":  {"title": "I Wanna Be in the Movies", "artist": "Frank Sinatra (or any movie-theme song)", "why": "Imperativos + tipos de filme."},
        "PE4": {"title": "September", "artist": "Earth, Wind & Fire", "why": "Meses + datas (‘Do you remember the 21st night of September?’)."},
        "8A":  {"title": "I Can See Clearly Now", "artist": "Johnny Nash", "why": "Uso afirmativo de can."},
        "8B":  {"title": "I Love Rock 'n' Roll", "artist": "Joan Jett", "why": "Like / love + atividade (rock 'n' roll)."},
        "9A":  {"title": "What a Wonderful World", "artist": "Louis Armstrong", "why": "Presente contínuo descrevendo o que está acontecendo agora."},
        "9B":  {"title": "Uniform", "artist": "Bloc Party", "why": "Roupas + present continuous vs simple."},
        "PE5": {"title": "Would You Like to Take a Walk", "artist": "Eddie Cantor", "why": "Convites com Would you like…?"},
        "10A": {"title": "Hotel California", "artist": "Eagles", "why": "Hotéis, there is / there are some… (clássico)."},
        "10B": {"title": "Yesterday", "artist": "The Beatles", "why": "Passado simples; ‘yesterday all my troubles seemed so far away’."},
        "11A": {"title": "American Pie", "artist": "Don McLean", "why": "Past simple regular; narrativa de uma vida nos EUA."},
        "11B": {"title": "It Was a Good Day", "artist": "Ice Cube", "why": "Past simple irregular (go/have/do) numa narrativa de um dia."},
        "PE6": {"title": "The Long and Winding Road", "artist": "The Beatles", "why": "Direções; metáfora de caminho."},
        "12A": {"title": "Strangers in the Night", "artist": "Frank Sinatra", "why": "‘Strangers’ no título + narrativa no passado."},
        "12B": {"title": "Those Were the Days", "artist": "Mary Hopkin", "why": "Revisão geral do passado."},
    },
    "elementary": {
        "1A":  {"title": "Hello, Goodbye", "artist": "The Beatles", "why": "Verb be + greetings."},
        "1B":  {"title": "Where Are You Now?", "artist": "Mumford & Sons", "why": "Países / where are you from? he/she/it."},
        "1C":  {"title": "What's My Name", "artist": "Snoop Dogg", "why": "Personal info, possessive adjectives (my, your)."},
        "PE1": {"title": "Hotel Yorba", "artist": "The White Stripes", "why": "Checking in / vocabulary de hotel."},
        "2A":  {"title": "My Room", "artist": "Boris Gardiner", "why": "Coisas em casa, neat / messy room."},
        "2B":  {"title": "Born in the U.S.A.", "artist": "Bruce Springsteen", "why": "Adjetivos + ícones americanos."},
        "2C":  {"title": "Slow Down", "artist": "Selena Gomez", "why": "Título = ‘Slow Down’; imperativos."},
        "3A":  {"title": "We Didn't Start the Fire", "artist": "Billy Joel", "why": "Vida nos EUA + presente simples + tons de vocab."},
        "3B":  {"title": "Working 9 to 5", "artist": "Dolly Parton", "why": "Jobs + perguntas no simple present."},
        "3C":  {"title": "Who Loves You", "artist": "Frankie Valli", "why": "Questões com question words + know somebody."},
        "PE2": {"title": "Black Coffee", "artist": "Peggy Lee", "why": "Buying a coffee."},
        "4A":  {"title": "Family Affair", "artist": "Sly & The Family Stone", "why": "Família + possessive 's."},
        "4B":  {"title": "Manic Monday", "artist": "The Bangles", "why": "Rotina diária + prepositions of time."},
        "4C":  {"title": "Forever Young", "artist": "Alphaville", "why": "Lifestyle, longevidade; tema das Blue Zones."},
        "5A":  {"title": "Imagine", "artist": "John Lennon", "why": "Can; verb phrases + visão de mundo."},
        "5B":  {"title": "The Sound of Silence", "artist": "Simon & Garfunkel", "why": "Barulho vs. silêncio + present continuous."},
        "5C":  {"title": "Sweet Home Chicago", "artist": "Robert Johnson", "why": "Chicago — cidade-tema da lição."},
        "PE3": {"title": "Material Girl", "artist": "Madonna", "why": "Comprar roupas + vocabulário de moda."},
        "6A":  {"title": "Tell Me a Story", "artist": "Phillip Phillips", "why": "Object pronouns + uma história narrada."},
        "6B":  {"title": "Friday I'm in Love", "artist": "The Cure", "why": "Dias da semana + like + verb-ing."},
        "6C":  {"title": "Don't Stop the Music", "artist": "Rihanna", "why": "Música como tema; review be/do."},
        "7A":  {"title": "Tubthumping", "artist": "Chumbawamba", "why": "Past simple was/were — ‘I get knocked down…’."},
        "7B":  {"title": "Hooray for Hollywood", "artist": "Various", "why": "Past simple regular + cinema."},
        "7C":  {"title": "Happy New Year", "artist": "ABBA", "why": "Past irregular + tema da virada do ano."},
        "PE4": {"title": "On the Road Again", "artist": "Willie Nelson", "why": "Direções e jornada."},
        "8A":  {"title": "Murder Was the Case", "artist": "Snoop Dogg (clean)", "why": "Revisão geral do passado em narrativa."},
        "8B":  {"title": "Our House", "artist": "Madness", "why": "There is/are + tipos de quartos e móveis."},
        "8C":  {"title": "Ghost", "artist": "Justin Bieber", "why": "There was/were + tema de assombração."},
        "9A":  {"title": "Eat It", "artist": "Weird Al Yankovic", "why": "Comida + countable / uncountable."},
        "9B":  {"title": "Sugar", "artist": "Maroon 5", "why": "Sugar/salt como tema; quantifiers."},
        "9C":  {"title": "99 Problems", "artist": "Jay-Z (clean)", "why": "Números altos + comparatives."},
        "PE5": {"title": "I Want to Eat", "artist": "Caro Emerald", "why": "Ordering a meal."},
        "10A": {"title": "Stairway to Heaven", "artist": "Led Zeppelin", "why": "Superlativos + descrição de lugares."},
        "10B": {"title": "Around the World", "artist": "Daft Punk", "why": "Be going to + planos de viagem."},
        "10C": {"title": "The Future's So Bright", "artist": "Timbuk 3", "why": "Be going to (predictions)."},
        "11A": {"title": "Englishman in New York", "artist": "Sting", "why": "Culture shock no exterior."},
        "11B": {"title": "Dreamer", "artist": "Supertramp", "why": "Verb + infinitive — sonhos e ambições."},
        "11C": {"title": "Hello", "artist": "Lionel Richie", "why": "Definite article + telefone/contato."},
        "PE6": {"title": "Slow Train Coming", "artist": "Bob Dylan", "why": "Transporte público."},
        "12A": {"title": "I've Seen It All", "artist": "Björk", "why": "Present perfect com ever — tema direto da lição."},
        "12B": {"title": "Been Around the World", "artist": "Puff Daddy", "why": "Present perfect vs simple past."},
        "12C": {"title": "Goodbye Yellow Brick Road", "artist": "Elton John", "why": "Question formation + fechamento de curso."},
    },
    "pre-intermediate": {
        "1A":  {"title": "Are You Gonna Be My Girl", "artist": "Jet", "why": "Word order in questions."},
        "1B":  {"title": "Perfect", "artist": "Ed Sheeran", "why": "Simple present + descrição de pessoa."},
        "1C":  {"title": "She's a Rainbow", "artist": "The Rolling Stones", "why": "Present continuous + descrição visual."},
        "PE1": {"title": "Hotel California", "artist": "Eagles", "why": "Hotel problems."},
        "2A":  {"title": "Holiday", "artist": "Madonna", "why": "Past simple narrativa de viagem."},
        "2B":  {"title": "Paparazzi", "artist": "Lady Gaga", "why": "Past continuous + photos / story by photo."},
        "2C":  {"title": "Dark Horse", "artist": "Katy Perry", "why": "Past simple e past continuous numa história com twist."},
        "3A":  {"title": "Leaving on a Jet Plane", "artist": "John Denver", "why": "Going to + airport."},
        "3B":  {"title": "Tomorrow Never Knows", "artist": "The Beatles", "why": "Present continuous para futuro."},
        "3C":  {"title": "Anything Goes", "artist": "Cole Porter", "why": "Defining relative clauses + word games."},
        "PE2": {"title": "Dinner for Two", "artist": "Carla Bruni", "why": "Ordering at the restaurant."},
        "4A":  {"title": "Started", "artist": "Iggy Azalea", "why": "Present perfect + yet / already (housework)."},
        "4B":  {"title": "Material Girl", "artist": "Madonna", "why": "Shopping + present perfect."},
        "4C":  {"title": "Saturday in the Park", "artist": "Chicago", "why": "Weekend memories + something/nothing."},
        "5A":  {"title": "Faster", "artist": "Within Temptation", "why": "Pace of life + comparatives."},
        "5B":  {"title": "The Best", "artist": "Tina Turner", "why": "Superlativos puros."},
        "5C":  {"title": "Too Much", "artist": "Spice Girls", "why": "Quantifiers too much / enough."},
        "PE3": {"title": "Return to Sender", "artist": "Elvis Presley", "why": "Taking something back to a store."},
        "6A":  {"title": "Don't Worry, Be Happy", "artist": "Bobby McFerrin", "why": "Optimist / will + predictions."},
        "6B":  {"title": "I Will Always Love You", "artist": "Whitney Houston", "why": "Will para promessas."},
        "6C":  {"title": "Dream a Little Dream of Me", "artist": "The Mamas & The Papas", "why": "Sonhos + revisão de tempos verbais."},
        "7A":  {"title": "Manic Monday", "artist": "The Bangles", "why": "First day / stressful situations + infinitive."},
        "7B":  {"title": "Happy", "artist": "Pharrell Williams", "why": "Gerunds + felicidade."},
        "7C":  {"title": "Lose Yourself", "artist": "Eminem", "why": "Obrigações + have to / must."},
        "PE4": {"title": "Comfortably Numb", "artist": "Pink Floyd", "why": "Indo à farmácia / sintomas."},
        "8A":  {"title": "You Should Be Dancing", "artist": "Bee Gees", "why": "Should para dar conselho."},
        "8B":  {"title": "Que Sera, Sera", "artist": "Doris Day", "why": "First conditional + Murphy's Law."},
        "8C":  {"title": "I Heard It Through the Grapevine", "artist": "Marvin Gaye", "why": "Possessive pronouns + history twist."},
        "9A":  {"title": "Eye of the Tiger", "artist": "Survivor", "why": "Second conditional em situação de animais perigosos."},
        "9B":  {"title": "Don't Be Scared", "artist": "Andy Mineo", "why": "Phobias + present perfect."},
        "9C":  {"title": "My Way", "artist": "Frank Sinatra", "why": "Biografia + simple past vs present perfect."},
        "PE5": {"title": "Direction", "artist": "BTS (or any directional song)", "why": "Asking for directions."},
        "10A": {"title": "Walk This Way", "artist": "Aerosmith / Run DMC", "why": "Express movement com prepositions."},
        "10B": {"title": "Wake Up Boo!", "artist": "The Boo Radleys", "why": "Phrasal verbs + early morning."},
        "10C": {"title": "Imagine", "artist": "John Lennon", "why": "Inventions and the present/past passive."},
        "11A": {"title": "School Days", "artist": "Chuck Berry", "why": "Used to + memórias de escola."},
        "11B": {"title": "Should I Stay or Should I Go", "artist": "The Clash", "why": "Might / possibilidade."},
        "11C": {"title": "Twin Souls", "artist": "Bond", "why": "Gêmeos + So am I / Neither am I."},
        "PE6": {"title": "Telephone", "artist": "Lady Gaga", "why": "Calling, leaving messages."},
        "12A": {"title": "Tell Me a Story", "artist": "Phillip Phillips", "why": "Past perfect em strange but true stories."},
        "12B": {"title": "Rumour Has It", "artist": "Adele", "why": "Reported speech + gossip."},
        "12C": {"title": "Question", "artist": "The Moody Blues", "why": "Question formation."},
    },
    "intermediate": {
        "1A":  {"title": "Eat It", "artist": "Weird Al Yankovic", "why": "Comida + simple present / continuous."},
        "1B":  {"title": "We Are Family", "artist": "Sister Sledge", "why": "Família + future forms."},
        "PE1": {"title": "Father and Son", "artist": "Cat Stevens", "why": "Reacting to what people say."},
        "2A":  {"title": "Money", "artist": "Pink Floyd", "why": "Money + present perfect vs simple past."},
        "2B":  {"title": "Changes", "artist": "David Bowie", "why": "Present perfect continuous + changing lives."},
        "3A":  {"title": "On the Road Again", "artist": "Willie Nelson", "why": "Transporte rodoviário + comparatives."},
        "3B":  {"title": "Girls Just Want to Have Fun", "artist": "Cyndi Lauper", "why": "Gender stereotypes + articles."},
        "PE2": {"title": "I Have a Dream", "artist": "ABBA", "why": "Expressing opinions e agreeing."},
        "4A":  {"title": "Bad", "artist": "Michael Jackson", "why": "Manners/bad behavior + must/have to/should."},
        "4B":  {"title": "Can't Get Enough of Your Love", "artist": "Barry White", "why": "Be able to + abilidades."},
        "5A":  {"title": "We Are the Champions", "artist": "Queen", "why": "Sports + narrative tenses."},
        "5B":  {"title": "Used to Be", "artist": "Beyoncé", "why": "Used to + relacionamentos."},
        "PE3": {"title": "Please Mr. Postman", "artist": "The Marvelettes", "why": "Asking for permission and requests."},
        "6A":  {"title": "Behind the Scenes", "artist": "James Brown", "why": "Movies + passive forms."},
        "6B":  {"title": "Body Language", "artist": "Queen", "why": "Modals of deduction + appearance."},
        "7A":  {"title": "Another Brick in the Wall", "artist": "Pink Floyd", "why": "Education + first conditional."},
        "7B":  {"title": "Our House", "artist": "Madness", "why": "Houses + second conditional."},
        "PE4": {"title": "Suggestion Box", "artist": "Phish", "why": "Making suggestions."},
        "8A":  {"title": "Working for the Weekend", "artist": "Loverboy", "why": "Work + gerund vs infinitive."},
        "8B":  {"title": "Complaint Department", "artist": "Boss Hog", "why": "Customer service + reported speech."},
        "9A":  {"title": "Lucky", "artist": "Jason Mraz & Colbie Caillat", "why": "Third conditional + luck."},
        "9B":  {"title": "Disconnect", "artist": "Clean Bandit", "why": "Quantifiers + digital detox."},
        "PE5": {"title": "Indirect", "artist": "PVRIS", "why": "Indirect questions."},
        "10A": {"title": "Vincent (Starry, Starry Night)", "artist": "Don McLean", "why": "Icons (referência a Van Gogh)."},
        "10B": {"title": "Murder by Numbers", "artist": "The Police", "why": "Murder mysteries + tag questions."},
    },
    "upper-intermediate": {
        "1A":  {"title": "Questions 67 & 68", "artist": "Chicago", "why": "Question formation no título literal."},
        "1B":  {"title": "Mystery", "artist": "Anita Baker", "why": "Mistério + auxiliares de ênfase."},
        "CE1": {"title": "Working 9 to 5", "artist": "Dolly Parton", "why": "Getting a job — tema da Colloquial."},
        "2A":  {"title": "Doctor My Eyes", "artist": "Jackson Browne", "why": "Medicina + present perfect."},
        "2B":  {"title": "Forever Young", "artist": "Bob Dylan", "why": "Age + adjective order."},
        "3A":  {"title": "Leaving on a Jet Plane", "artist": "John Denver", "why": "Air travel + narrative tenses."},
        "3B":  {"title": "Tell Me a Story", "artist": "Phillip Phillips", "why": "Stories + adverbs e adverbial phrases."},
        "CE2": {"title": "Paperback Writer", "artist": "The Beatles", "why": "Books — tema da Colloquial."},
        "4A":  {"title": "What a Wonderful World", "artist": "Louis Armstrong", "why": "Environment + future perfect/continuous."},
        "4B":  {"title": "Roll the Dice", "artist": "Bukowski/Macklemore", "why": "Risk + conditionals."},
        "5A":  {"title": "I Will Survive", "artist": "Gloria Gaynor", "why": "Survival + unreal conditionals."},
        "5B":  {"title": "Wish You Were Here", "artist": "Pink Floyd", "why": "Wish + regrets — título literal."},
        "CE3": {"title": "Plastic Love", "artist": "Mariya Takeuchi", "why": "Plastic / waste — tema da Colloquial."},
        "6A":  {"title": "Mr. Sandman", "artist": "The Chordettes", "why": "Sleep + used to / be used to."},
        "6B":  {"title": "Music to Watch Girls By", "artist": "Andy Williams", "why": "Music — tema literal + gerunds/infinitives."},
        "7A":  {"title": "Let's Call the Whole Thing Off", "artist": "Ella Fitzgerald & Louis Armstrong", "why": "Argumentos + past modals."},
        "7B":  {"title": "Body Language", "artist": "Queen", "why": "Body language + verbs of the senses."},
        "CE4": {"title": "Theatre Mode", "artist": "Various", "why": "Performances — tema da Colloquial."},
        "8A":  {"title": "Smooth Criminal", "artist": "Michael Jackson", "why": "Crime + causative have."},
        "8B":  {"title": "Dirty Laundry", "artist": "Don Henley", "why": "Media + fake news (clássico)."},
        "9A":  {"title": "Money for Nothing", "artist": "Dire Straits", "why": "Business + advertising."},
        "9B":  {"title": "New York, New York", "artist": "Frank Sinatra", "why": "Cities + uncountable nouns."},
        "CE5": {"title": "Don't Stand So Close to Me", "artist": "The Police", "why": "Advertising influence — tema CE."},
        "10A": {"title": "Rocket Man", "artist": "Elton John", "why": "Science / sci-fi + quantifiers."},
        "10B": {"title": "Imagine", "artist": "John Lennon", "why": "Public speech mais famoso da história pop + articles."},
    },
    "advanced": {
        "1A":  {"title": "We Are Family", "artist": "Sister Sledge", "why": "Family + uses of have."},
        "1B":  {"title": "Working 9 to 5", "artist": "Dolly Parton", "why": "Work + linkers."},
        "CE1": {"title": "Family Affair", "artist": "Sly & The Family Stone", "why": "Family & work — tema CE."},
        "2A":  {"title": "Tongue Tied", "artist": "Grouplove", "why": "Language + pronouns."},
        "2B":  {"title": "Yesterday", "artist": "The Beatles", "why": "Childhood memories + past forms."},
        "3A":  {"title": "I Will Survive", "artist": "Gloria Gaynor", "why": "Break-up + uses of get."},
        "3B":  {"title": "We Didn't Start the Fire", "artist": "Billy Joel", "why": "History / historical movies — vocab de conflito."},
        "CE2": {"title": "1492", "artist": "Vangelis", "why": "History — tema CE."},
        "4A":  {"title": "The Sound of Silence", "artist": "Simon & Garfunkel", "why": "Noise + silence — direto."},
        "4B":  {"title": "Paperback Writer", "artist": "The Beatles", "why": "Books + inversion."},
        "5A":  {"title": "Time After Time", "artist": "Cyndi Lauper", "why": "Time + distancing language."},
        "5B":  {"title": "Money for Nothing", "artist": "Dire Straits", "why": "Money / materialism + I wish."},
        "CE3": {"title": "Under Pressure", "artist": "Queen & David Bowie", "why": "Stress — tema CE."},
        "6A":  {"title": "Don't Worry, Be Happy", "artist": "Bobby McFerrin", "why": "Coping + verb + object + inf/-ing."},
        "6B":  {"title": "Smartphone", "artist": "Trey Songz", "why": "Behavioral addiction (phone)."},
        "7A":  {"title": "Won't Get Fooled Again", "artist": "The Who", "why": "Control + modals (permission/obligation)."},
        "7B":  {"title": "Vincent (Starry, Starry Night)", "artist": "Don McLean", "why": "Art + verbs of the senses."},
        "CE4": {"title": "Pencil Full of Lead", "artist": "Paolo Nutini", "why": "Illustration as life — tema CE."},
        "8A":  {"title": "Doctor My Eyes", "artist": "Jackson Browne", "why": "Health + gerunds/infinitives avançados."},
        "8B":  {"title": "Holiday", "artist": "Madonna", "why": "Travel + future plans."},
        "9A":  {"title": "Eye of the Tiger", "artist": "Survivor", "why": "Animals + ellipsis."},
        "9B":  {"title": "Sugar, We're Goin Down", "artist": "Fall Out Boy", "why": "Food + compound nouns."},
        "CE5": {"title": "Birds of a Feather", "artist": "Billie Eilish", "why": "Wild nature — tema CE."},
        "10A": {"title": "American Land", "artist": "Bruce Springsteen", "why": "Emigração + cleft sentences."},
        "10B": {"title": "We Will Rock You", "artist": "Queen", "why": "Sports + relative clauses."},
    },
}
